[tool.poetry]
name = "ppo"
version = "0.1.0"
description = ""
authors = ["Eugene Teoh <eugenetwc1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
torch = {version = "^1.10.1", platform = "linux"}
gym = {version = "^0.21.0", extras = ["atari", "accept-rom-license"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
